-- ============================================================
-- [HAHA LAB] Supabase Integrated Database Schema
-- Ver: Final Complete v3.2 (Updated 2026-02-10)
-- - Admin Features, Storage, RLS included
-- - Schedule status enhancements for completed tracking
-- - Client status management (active, paused, terminated, deleted)
-- - Histories tracking with YYYYMMDD HH:mm format
-- - Session/Consultation history tracking with time calculations
-- ============================================================

-- ============================================================
-- [TABLE DEFINITIONS]
-- ============================================================

-- 1. 선생님 (Teachers) 테이블
CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT UNIQUE NOT NULL, -- 로그인 ID
    password TEXT NOT NULL,          -- 비밀번호 (실제 프로덕션에서는 해싱 필요)
    name TEXT NOT NULL,
    center TEXT,
    gender TEXT,
    age INT,
    contact TEXT,
    email TEXT,
    plan TEXT DEFAULT 'Basic Plan',  -- 'Basic Plan', 'Pro Plan', 'Enterprise'
    status TEXT DEFAULT 'Active',    -- 'Active', 'Paused', 'Suspended'
    memo TEXT,
    registered_clients INT DEFAULT 0
);

-- 2. 내담자 (Clients) 테이블
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,        -- 담당 선생님 ID
    name TEXT NOT NULL,
    type TEXT NOT NULL,              -- 'client'(정규), 'reserve'(대기)
    status TEXT DEFAULT 'active',    -- 'active', 'paused', 'terminated', 'deleted'
    gender TEXT,
    dob TEXT,                        -- YYYY-MM-DD 형식
    age INT,
    contact TEXT,
    address TEXT,
    guardians JSONB,                 -- 보호자 정보 (JSON 배열)
    session_time INT DEFAULT 50,     -- 기본 수업 시간 (분)
    diagnosis TEXT,
    initial_consult TEXT,
    areas JSONB,                     -- 발달 영역 태그 정보 {lang:[], cogn:[], behv:[]}
    memo TEXT,
    reserve_date TEXT,               -- 상담 예약 날짜 (reserve 타입인 경우)
    reserve_time TEXT                -- 상담 예약 시간 (reserve 타입인 경우)
);

-- 3. 스케줄 (Schedules) 테이블
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL,              -- 'client'(수업), 'reserve'(상담)
    date TEXT NOT NULL,              -- YYYY-MM-DD 형식
    start_time TEXT NOT NULL,        -- HH:MM 형식
    end_time TEXT NOT NULL,          -- HH:MM 형식
    status TEXT DEFAULT 'scheduled', -- 'scheduled', 'completed', 'noshow', 'deleted', 'changed'
    memo TEXT
);

-- 4. 공지사항 (Notices) 테이블
CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    type TEXT NOT NULL,              -- '일반', '업데이트', '점검', '이벤트'
    title TEXT NOT NULL,
    content TEXT,                    -- HTML 포함 가능
    date TEXT,                       -- 공지 날짜 (YYYY-MM-DD)
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 5. Play Lab 콘텐츠 (Play Contents) 테이블
CREATE TABLE IF NOT EXISTS play_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    cat_id TEXT NOT NULL,            -- 'think', 'sound', 'listen', 'see', 'speak', 'life', 'art'
    title TEXT NOT NULL,
    url TEXT,
    tags TEXT[],                     -- PostgreSQL Array Type
    thumbnail TEXT,
    views INT DEFAULT 0,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 6. 활동 로그 (Activity Logs) 테이블
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_name TEXT,
    center_name TEXT,
    type TEXT,                       -- '시스템', '수업', '학생관리', '상담'
    action TEXT,                     -- '로그인', '수업완료', '상담완료', '학생추가' 등
    details TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 7. 내담자/예약자 이력 (Histories) 테이블 - UPDATED v3.2
CREATE TABLE IF NOT EXISTS histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,        -- 담당 선생님 ID
    client_id TEXT NOT NULL,         -- 내담자/예약자 ID
    client_name TEXT NOT NULL,       -- 이름
    type TEXT NOT NULL,              -- 'session', 'consultation', 'noshow', 'reschedule', 'delete'
    category TEXT NOT NULL,          -- 'session_history'(수업이력), 'consultation_history'(상담이력)
    action TEXT NOT NULL,            -- '수업완료', '상담완료', '일정변경', '미출석', '일정삭제'
    
    -- YYYYMMDD HH:mm 형식 저장 필드
    event_datetime TEXT,             -- 이벤트 발생 시각 (YYYYMMDD HH:mm)
    start_datetime TEXT,             -- 시작 시각 (YYYYMMDD HH:mm)
    end_datetime TEXT,               -- 종료 시각 (YYYYMMDD HH:mm)
    noshow_datetime TEXT,            -- 미출석 처리 시각 (YYYYMMDD HH:mm)
    delete_datetime TEXT,            -- 삭제 처리 시각 (YYYYMMDD HH:mm)
    reschedule_datetime TEXT,        -- 일정 변경 시각 (YYYYMMDD HH:mm)
    original_datetime TEXT,          -- 원래 일정 (YYYYMMDD HH:mm)
    changed_datetime TEXT,           -- 변경된 일정 (YYYYMMDD HH:mm)
    
    duration_minutes INT,            -- 총 소요 시간 (분)
    details TEXT,                    -- 추가 상세 정보
    memo TEXT                        -- 메모
);


-- ============================================================
-- [INDEXES] 성능 최적화를 위한 인덱스
-- ============================================================

-- Teachers 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_teachers_teacher_id ON teachers(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teachers_status ON teachers(status);

-- Clients 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_clients_teacher_id ON clients(teacher_id);
CREATE INDEX IF NOT EXISTS idx_clients_type ON clients(type);
CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status);
CREATE INDEX IF NOT EXISTS idx_clients_name ON clients(name);

-- Schedules 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_schedules_teacher_id ON schedules(teacher_id);
CREATE INDEX IF NOT EXISTS idx_schedules_client_id ON schedules(client_id);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date);
CREATE INDEX IF NOT EXISTS idx_schedules_status ON schedules(status);
CREATE INDEX IF NOT EXISTS idx_schedules_type ON schedules(type);
CREATE INDEX IF NOT EXISTS idx_schedules_date_time ON schedules(date, start_time);

-- Play Contents 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_play_contents_cat_id ON play_contents(cat_id);
CREATE INDEX IF NOT EXISTS idx_play_contents_is_hidden ON play_contents(is_hidden);

-- Notices 테이블 인덱스
CREATE INDEX IF NOT EXISTS idx_notices_type ON notices(type);
CREATE INDEX IF NOT EXISTS idx_notices_is_hidden ON notices(is_hidden);

-- Histories 테이블 인덱스 - NEW
CREATE INDEX IF NOT EXISTS idx_histories_teacher_id ON histories(teacher_id);
CREATE INDEX IF NOT EXISTS idx_histories_client_id ON histories(client_id);
CREATE INDEX IF NOT EXISTS idx_histories_category ON histories(category);
CREATE INDEX IF NOT EXISTS idx_histories_date ON histories(date);
CREATE INDEX IF NOT EXISTS idx_histories_type ON histories(type);


-- ============================================================
-- [Safety Checks] 기존 테이블 구조 보정
-- (테이블이 이미 생성된 경우, 누락된 핵심 컬럼 추가)
-- ============================================================
DO $$
BEGIN
    -- teachers 테이블에 status 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='teachers' AND column_name='status') THEN
        ALTER TABLE teachers ADD COLUMN status TEXT DEFAULT 'Active';
    END IF;
    
    -- notices 테이블에 is_hidden 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notices' AND column_name='is_hidden') THEN
        ALTER TABLE notices ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
    END IF;
    
    -- notices 테이블에 updated_at 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notices' AND column_name='updated_at') THEN
        ALTER TABLE notices ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW());
    END IF;
    
    -- play_contents 테이블에 is_hidden 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='play_contents' AND column_name='is_hidden') THEN
        ALTER TABLE play_contents ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
    END IF;
    
    -- schedules 테이블 status 기본값 확인
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='schedules' AND column_name='status') THEN
        ALTER TABLE schedules ADD COLUMN status TEXT DEFAULT 'scheduled';
    END IF;
    
    -- clients 테이블 status 기본값 확인
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='status') THEN
        ALTER TABLE clients ADD COLUMN status TEXT DEFAULT 'active';
    END IF;
END $$;


-- ============================================================
-- [Data Integrity] 데이터 정합성 유지
-- ============================================================

-- 1. 삭제된 내담자의 스케줄(고아 데이터) 제거
DELETE FROM schedules 
WHERE client_id NOT IN (SELECT id::text FROM clients) 
AND client_id IS NOT NULL;

-- 2. status 필드 정규화 (대소문자 통일)
UPDATE teachers SET status = 'Active' WHERE LOWER(status) = 'active';
UPDATE teachers SET status = 'Paused' WHERE LOWER(status) = 'paused';
UPDATE teachers SET status = 'Suspended' WHERE LOWER(status) = 'suspended';

UPDATE clients SET status = 'active' WHERE status IS NULL OR status = '';
UPDATE schedules SET status = 'scheduled' WHERE status IS NULL OR status = '';


-- ============================================================
-- [Storage] 버킷 설정 및 정책
-- ============================================================

-- 'images' 버킷 생성 (이미 존재하면 무시)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) 
VALUES (
    'images', 
    'images', 
    true,
    15728640, -- 15MB 제한
    ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE
SET 
    public = true,
    file_size_limit = 15728640,
    allowed_mime_types = ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']::text[];

-- 스토리지 정책 초기화 (중복 방지)
DROP POLICY IF EXISTS "Public Access Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Images" ON storage.objects;

-- 스토리지 정책 생성 (읽기/쓰기/삭제 허용)
CREATE POLICY "Public Access Images" 
    ON storage.objects FOR SELECT 
    USING ( bucket_id = 'images' );

CREATE POLICY "Public Insert Images" 
    ON storage.objects FOR INSERT 
    WITH CHECK ( bucket_id = 'images' );

CREATE POLICY "Public Update Images" 
    ON storage.objects FOR UPDATE 
    USING ( bucket_id = 'images' )
    WITH CHECK ( bucket_id = 'images' );

CREATE POLICY "Public Delete Images" 
    ON storage.objects FOR DELETE 
    USING ( bucket_id = 'images' );


-- ============================================================
-- [Security] RLS (Row Level Security) 설정
-- 개발 편의를 위해 '모든 접근 허용(Allow All)' 정책 적용
-- 프로덕션에서는 teacher_id 기반 필터링 권장
-- ============================================================

-- 1. 테이블 RLS 활성화
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE play_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE histories ENABLE ROW LEVEL SECURITY;

-- 2. 기존 정책 삭제 (에러 방지)
DROP POLICY IF EXISTS "Allow All Teachers" ON teachers;
DROP POLICY IF EXISTS "Allow All Clients" ON clients;
DROP POLICY IF EXISTS "Allow All Schedules" ON schedules;
DROP POLICY IF EXISTS "Allow All Notices" ON notices;
DROP POLICY IF EXISTS "Allow All Contents" ON play_contents;
DROP POLICY IF EXISTS "Allow All Logs" ON activity_logs;
DROP POLICY IF EXISTS "Allow All Histories" ON histories;

-- 이전 버전 정책 이름도 삭제 시도
DROP POLICY IF EXISTS "Allow All Access Teachers" ON teachers;
DROP POLICY IF EXISTS "Allow All Access Clients" ON clients;
DROP POLICY IF EXISTS "Allow All Access Schedules" ON schedules;
DROP POLICY IF EXISTS "Allow All Access Notices" ON notices;
DROP POLICY IF EXISTS "Allow All Access Contents" ON play_contents;
DROP POLICY IF EXISTS "Allow All Access Logs" ON activity_logs;

-- 3. '모든 사용자에게 모든 권한 허용' 정책 생성
CREATE POLICY "Allow All Teachers" 
    ON teachers FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Clients" 
    ON clients FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Schedules" 
    ON schedules FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Notices" 
    ON notices FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Contents" 
    ON play_contents FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Logs" 
    ON activity_logs FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Histories" 
    ON histories FOR ALL 
    USING (true) 
    WITH CHECK (true);


-- ============================================================
-- [SAMPLE DATA] 테스트용 샘플 데이터 (선택적 실행)
-- ============================================================

-- 샘플 선생님 데이터
INSERT INTO teachers (teacher_id, password, name, center, gender, age, contact, email, plan, status, registered_clients)
VALUES 
    ('teacher01', '1234', '김은애', '강남 본점', '여', 32, '010-1234-5678', 'kim@example.com', 'Pro Plan', 'Active', 8),
    ('teacher02', '1234', '이준호', '서초점', '남', 29, '010-2345-6789', 'lee@example.com', 'Basic Plan', 'Active', 5)
ON CONFLICT (teacher_id) DO NOTHING;

-- 샘플 공지사항
INSERT INTO notices (type, title, content, date, is_hidden)
VALUES 
    ('업데이트', '새로운 기능 업데이트 안내', '<p>스케줄 완료 상태 표시 기능이 추가되었습니다.</p><p>- 완료된 수업/상담은 회색으로 표시됩니다.</p><p>- 완료 처리 버튼이 추가되었습니다.</p>', '2026-02-10', false),
    ('일반', 'HAHA LAB 시스템 오픈', '<p>HAHA LAB 시스템이 정식 오픈되었습니다.</p><p>많은 이용 부탁드립니다.</p>', '2026-01-15', false)
ON CONFLICT DO NOTHING;

-- 샘플 Play Lab 콘텐츠
INSERT INTO play_contents (cat_id, title, url, tags, views, is_hidden)
VALUES 
    ('think', '기억력 향상 게임', 'https://example.com/memory-game', ARRAY['기억력', '인지', '주의력'], 120, false),
    ('sound', '음소 인식 훈련', 'https://example.com/phoneme-training', ARRAY['음소', '발음', '언어'], 85, false),
    ('listen', '청각 변별 훈련', 'https://example.com/auditory-training', ARRAY['청각', '집중력', '변별'], 95, false)
ON CONFLICT DO NOTHING;


-- ============================================================
-- [FUNCTIONS] 유용한 함수들 (선택적)
-- ============================================================

-- 특정 날짜의 스케줄 조회 함수
CREATE OR REPLACE FUNCTION get_schedules_by_date(p_teacher_id TEXT, p_date TEXT)
RETURNS TABLE (
    id BIGINT,
    client_name TEXT,
    type TEXT,
    start_time TEXT,
    end_time TEXT,
    status TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT s.id, s.client_name, s.type, s.start_time, s.end_time, s.status
    FROM schedules s
    WHERE s.teacher_id = p_teacher_id 
    AND s.date = p_date
    AND s.status != 'deleted'
    ORDER BY s.start_time;
END;
$$ LANGUAGE plpgsql;

-- 내담자 통계 조회 함수
CREATE OR REPLACE FUNCTION get_client_stats(p_teacher_id TEXT)
RETURNS TABLE (
    total_clients INT,
    active_clients INT,
    reserve_clients INT,
    paused_clients INT,
    terminated_clients INT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*)::INT AS total_clients,
        COUNT(CASE WHEN type = 'client' AND status = 'active' THEN 1 END)::INT AS active_clients,
        COUNT(CASE WHEN type = 'reserve' AND status = 'active' THEN 1 END)::INT AS reserve_clients,
        COUNT(CASE WHEN status = 'paused' THEN 1 END)::INT AS paused_clients,
        COUNT(CASE WHEN status = 'terminated' THEN 1 END)::INT AS terminated_clients
    FROM clients
    WHERE teacher_id = p_teacher_id
    AND status != 'deleted';
END;
$$ LANGUAGE plpgsql;

-- 내담자 수업시간 통계 조회 함수 (주간/월간/총)
CREATE OR REPLACE FUNCTION get_session_time_stats(p_client_id TEXT)
RETURNS TABLE (
    weekly_minutes INT,
    monthly_minutes INT,
    total_minutes INT
) AS $$
DECLARE
    week_start TEXT;
    month_start TEXT;
BEGIN
    -- 이번 주 시작 (월요일)
    week_start := TO_CHAR(DATE_TRUNC('week', CURRENT_DATE), 'YYYYMMDD');
    -- 이번 달 시작
    month_start := TO_CHAR(DATE_TRUNC('month', CURRENT_DATE), 'YYYYMMDD');
    
    RETURN QUERY
    SELECT 
        COALESCE(SUM(CASE 
            WHEN SUBSTRING(start_datetime, 1, 8) >= week_start 
            THEN duration_minutes 
            ELSE 0 
        END), 0)::INT AS weekly_minutes,
        COALESCE(SUM(CASE 
            WHEN SUBSTRING(start_datetime, 1, 8) >= month_start 
            THEN duration_minutes 
            ELSE 0 
        END), 0)::INT AS monthly_minutes,
        COALESCE(SUM(duration_minutes), 0)::INT AS total_minutes
    FROM histories
    WHERE client_id = p_client_id
    AND category = 'session_history'
    AND action = '수업완료'
    AND start_datetime IS NOT NULL;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- [TRIGGERS] 자동화 트리거
-- ============================================================

-- 스케줄 완료 시 활동 로그 및 이력 자동 생성 (YYYYMMDD HH:mm 형식)
CREATE OR REPLACE FUNCTION log_schedule_completion()
RETURNS TRIGGER AS $$
DECLARE
    duration_mins INT;
    start_dt TIMESTAMP;
    end_dt TIMESTAMP;
    start_fmt TEXT;
    end_fmt TEXT;
    now_fmt TEXT;
BEGIN
    -- 현재 시각을 YYYYMMDD HH:mm 형식으로
    now_fmt := TO_CHAR(TIMEZONE('Asia/Seoul', NOW()), 'YYYYMMDD HH24:MI');
    
    IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
        -- 소요 시간 계산
        start_dt := (NEW.date || ' ' || NEW.start_time)::TIMESTAMP;
        end_dt := (NEW.date || ' ' || NEW.end_time)::TIMESTAMP;
        duration_mins := EXTRACT(EPOCH FROM (end_dt - start_dt)) / 60;
        
        -- YYYYMMDD HH:mm 형식으로 변환
        start_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.start_time;
        end_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.end_time;
        
        -- 활동 로그 생성
        INSERT INTO activity_logs (teacher_name, center_name, type, action, details)
        SELECT 
            t.name,
            t.center,
            CASE WHEN NEW.type = 'reserve' THEN '상담' ELSE '수업' END,
            CASE WHEN NEW.type = 'reserve' THEN '상담완료' ELSE '수업완료' END,
            NEW.client_name || ' (' || start_fmt || ' ~ ' || end_fmt || ')'
        FROM teachers t
        WHERE t.teacher_id = NEW.teacher_id;
        
        -- 이력 생성
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            event_datetime, start_datetime, end_datetime, duration_minutes, 
            details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            CASE WHEN NEW.type = 'reserve' THEN 'consultation' ELSE 'session' END,
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            CASE WHEN NEW.type = 'reserve' THEN '상담완료' ELSE '수업완료' END,
            now_fmt,
            start_fmt,
            end_fmt,
            duration_mins,
            '정상 완료됨'
        );
    END IF;
    
    -- 미출석 처리 시 이력 생성
    IF NEW.status = 'noshow' AND OLD.status != 'noshow' THEN
        start_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.start_time;
        
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            event_datetime, start_datetime, noshow_datetime,
            details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            'noshow',
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            '미출석',
            now_fmt,
            start_fmt,
            now_fmt,
            '미출석 처리됨'
        );
    END IF;
    
    -- 일정 변경 시 이력 생성
    IF (NEW.date != OLD.date OR NEW.start_time != OLD.start_time) AND NEW.status != 'deleted' THEN
        start_fmt := REPLACE(OLD.date, '-', '') || ' ' || OLD.start_time;
        end_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.start_time;
        
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            event_datetime, original_datetime, changed_datetime, reschedule_datetime,
            details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            'reschedule',
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            '일정변경',
            now_fmt,
            start_fmt,
            end_fmt,
            now_fmt,
            '일정이 변경됨'
        );
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_log_schedule_completion ON schedules;
CREATE TRIGGER trigger_log_schedule_completion
    AFTER UPDATE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_completion();

-- 스케줄 삭제 시 이력 생성 (YYYYMMDD HH:mm 형식)
CREATE OR REPLACE FUNCTION log_schedule_deletion()
RETURNS TRIGGER AS $$
DECLARE
    start_fmt TEXT;
    now_fmt TEXT;
BEGIN
    -- YYYYMMDD HH:mm 형식으로 변환
    start_fmt := REPLACE(OLD.date, '-', '') || ' ' || OLD.start_time;
    now_fmt := TO_CHAR(TIMEZONE('Asia/Seoul', NOW()), 'YYYYMMDD HH24:MI');
    
    INSERT INTO histories (
        teacher_id, client_id, client_name, 
        type, category, action, 
        event_datetime, start_datetime, delete_datetime,
        details
    ) VALUES (
        OLD.teacher_id, 
        OLD.client_id, 
        OLD.client_name,
        'delete',
        CASE WHEN OLD.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
        '일정삭제',
        now_fmt,
        start_fmt,
        now_fmt,
        '스케줄이 삭제됨'
    );
    
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_log_schedule_deletion ON schedules;
CREATE TRIGGER trigger_log_schedule_deletion
    BEFORE DELETE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_deletion();

-- Notices 테이블 updated_at 자동 갱신 트리거
CREATE OR REPLACE FUNCTION update_notice_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_notice_timestamp ON notices;
CREATE TRIGGER trigger_update_notice_timestamp
    BEFORE UPDATE ON notices
    FOR EACH ROW
    EXECUTE FUNCTION update_notice_timestamp();


-- ============================================================
-- [SCHEMA VERSION]
-- ============================================================
COMMENT ON SCHEMA public IS 'HAHA LAB Database Schema v3.2 - Updated 2026-02-10';


-- ============================================================
-- [완료]
-- 데이터베이스 스키마 초기화가 완료되었습니다.
-- ============================================================
