-- =============================================
-- HAHA LAB Database Schema
-- Version: v4.0 (Final Complete)
-- Created: 2026-02-10
-- Purpose: Complete schema with all features including
--          - Consultation & Session unified history
--          - Calendar visibility management (soft delete)
--          - Reserve to Client migration with history preservation
--          - Enhanced schedule detail modal
-- =============================================

-- =============================================
-- 1. ENABLE EXTENSIONS
-- =============================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- 2. DROP EXISTING OBJECTS (Clean Start)
-- =============================================
DROP TRIGGER IF EXISTS trigger_log_schedule_completion ON schedules CASCADE;
DROP TRIGGER IF EXISTS trigger_log_schedule_deletion ON schedules CASCADE;
DROP TRIGGER IF EXISTS trigger_update_notice_timestamp ON notices CASCADE;

DROP FUNCTION IF EXISTS log_schedule_completion() CASCADE;
DROP FUNCTION IF EXISTS log_schedule_deletion() CASCADE;
DROP FUNCTION IF EXISTS get_schedules_by_date(TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_client_stats(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_session_time_stats(TEXT) CASCADE;

DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS histories CASCADE;
DROP TABLE IF EXISTS play_contents CASCADE;
DROP TABLE IF EXISTS notices CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;

-- =============================================
-- 3. CREATE TABLES
-- =============================================

-- 3.1 Teachers Table
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    teacher_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    center TEXT,
    gender TEXT,
    age INT,
    contact TEXT,
    email TEXT,
    plan TEXT DEFAULT 'Basic Plan',
    status TEXT DEFAULT 'Active',
    memo TEXT,
    registered_clients INT DEFAULT 0
);

-- 3.2 Clients Table
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    teacher_id TEXT NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('client', 'reserve')),
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed')),
    gender TEXT,
    dob TEXT,
    age INT,
    contact TEXT,
    address TEXT,
    guardians JSONB,
    session_time INT DEFAULT 50,
    diagnosis TEXT,
    initial_consult TEXT,
    areas JSONB,
    memo TEXT,
    reserve_date TEXT,
    reserve_time TEXT,
    converted_from_reserve BOOLEAN DEFAULT FALSE,
    original_reserve_id BIGINT
);

-- 3.3 Schedules Table
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    teacher_id TEXT NOT NULL REFERENCES teachers(teacher_id) ON DELETE CASCADE,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('session', 'consultation')),
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'noshow', 'deleted_from_calendar')),
    memo TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    is_visible_in_calendar BOOLEAN DEFAULT TRUE
);

-- 3.4 Notices Table
CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('notice', 'event', 'update', 'maintenance')),
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    date TEXT NOT NULL,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 3.5 Play Contents Table
CREATE TABLE play_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    cat_id INT NOT NULL CHECK (cat_id BETWEEN 1 AND 7),
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    tags TEXT[],
    thumbnail TEXT,
    views INT DEFAULT 0,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 3.6 Activity Logs Table
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    teacher_name TEXT,
    center_name TEXT,
    type TEXT NOT NULL,
    action TEXT NOT NULL,
    details TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- 3.7 Histories Table (통합 이력 - 수업 및 상담)
CREATE TABLE histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    teacher_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('session', 'consultation')),
    category TEXT NOT NULL CHECK (category IN ('completed', 'noshow', 'changed', 'deleted', 'deleted_from_calendar')),
    action TEXT NOT NULL,
    event_datetime TEXT,
    start_datetime TEXT,
    end_datetime TEXT,
    noshow_datetime TEXT,
    delete_datetime TEXT,
    reschedule_datetime TEXT,
    original_datetime TEXT,
    changed_datetime TEXT,
    duration_minutes INT,
    details TEXT,
    memo TEXT,
    schedule_id BIGINT,
    is_migrated_from_reserve BOOLEAN DEFAULT FALSE
);

-- =============================================
-- 4. CREATE INDEXES
-- =============================================

-- Teachers Indexes
CREATE INDEX idx_teachers_teacher_id ON teachers(teacher_id);
CREATE INDEX idx_teachers_status ON teachers(status);
CREATE INDEX idx_teachers_center ON teachers(center);

-- Clients Indexes
CREATE INDEX idx_clients_teacher_id ON clients(teacher_id);
CREATE INDEX idx_clients_type ON clients(type);
CREATE INDEX idx_clients_status ON clients(status);
CREATE INDEX idx_clients_name ON clients(name);
CREATE INDEX idx_clients_converted ON clients(converted_from_reserve);

-- Schedules Indexes
CREATE INDEX idx_schedules_teacher_id ON schedules(teacher_id);
CREATE INDEX idx_schedules_client_id ON schedules(client_id);
CREATE INDEX idx_schedules_date ON schedules(date);
CREATE INDEX idx_schedules_type ON schedules(type);
CREATE INDEX idx_schedules_status ON schedules(status);
CREATE INDEX idx_schedules_date_time ON schedules(date, start_time);
CREATE INDEX idx_schedules_visible ON schedules(is_visible_in_calendar);

-- Notices Indexes
CREATE INDEX idx_notices_type ON notices(type);
CREATE INDEX idx_notices_date ON notices(date);
CREATE INDEX idx_notices_hidden ON notices(is_hidden);

-- Play Contents Indexes
CREATE INDEX idx_play_contents_cat_id ON play_contents(cat_id);
CREATE INDEX idx_play_contents_hidden ON play_contents(is_hidden);

-- Activity Logs Indexes
CREATE INDEX idx_activity_logs_teacher_name ON activity_logs(teacher_name);
CREATE INDEX idx_activity_logs_type ON activity_logs(type);
CREATE INDEX idx_activity_logs_occurred_at ON activity_logs(occurred_at);

-- Histories Indexes
CREATE INDEX idx_histories_teacher_id ON histories(teacher_id);
CREATE INDEX idx_histories_client_id ON histories(client_id);
CREATE INDEX idx_histories_type ON histories(type);
CREATE INDEX idx_histories_category ON histories(category);
CREATE INDEX idx_histories_start_datetime ON histories(start_datetime);
CREATE INDEX idx_histories_schedule_id ON histories(schedule_id);
CREATE INDEX idx_histories_migrated ON histories(is_migrated_from_reserve);

-- =============================================
-- 5. ROW LEVEL SECURITY (RLS)
-- =============================================

ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE play_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE histories ENABLE ROW LEVEL SECURITY;

-- Development: Allow All Access (Production에서는 teacher_id 기반 필터링 권장)
CREATE POLICY "Allow All Teachers" ON teachers FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Clients" ON clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Schedules" ON schedules FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Notices" ON notices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Play Contents" ON play_contents FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Activity Logs" ON activity_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Histories" ON histories FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- 6. STORAGE SETUP
-- =============================================

-- Create images bucket if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies
DROP POLICY IF EXISTS "Public Access for Images" ON storage.objects;
DROP POLICY IF EXISTS "Allow Insert for Images" ON storage.objects;
DROP POLICY IF EXISTS "Allow Update for Images" ON storage.objects;
DROP POLICY IF EXISTS "Allow Delete for Images" ON storage.objects;

CREATE POLICY "Public Access for Images"
ON storage.objects FOR SELECT
USING (bucket_id = 'images');

CREATE POLICY "Allow Insert for Images"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'images' 
    AND (storage.foldername(name))[1] = 'public'
    AND (LOWER(RIGHT(name, 4)) IN ('.jpg', '.png', '.gif', '.webp') 
         OR LOWER(RIGHT(name, 5)) = '.jpeg')
);

CREATE POLICY "Allow Update for Images"
ON storage.objects FOR UPDATE
USING (bucket_id = 'images');

CREATE POLICY "Allow Delete for Images"
ON storage.objects FOR DELETE
USING (bucket_id = 'images');

-- =============================================
-- 7. FUNCTIONS
-- =============================================

-- 7.1 Get Schedules by Date
CREATE OR REPLACE FUNCTION get_schedules_by_date(
    p_teacher_id TEXT,
    p_date TEXT
)
RETURNS TABLE (
    id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    teacher_id TEXT,
    client_id TEXT,
    client_name TEXT,
    type TEXT,
    date TEXT,
    start_time TEXT,
    end_time TEXT,
    status TEXT,
    memo TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    is_visible_in_calendar BOOLEAN
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        s.id,
        s.created_at,
        s.teacher_id,
        s.client_id,
        s.client_name,
        s.type,
        s.date,
        s.start_time,
        s.end_time,
        s.status,
        s.memo,
        s.completed_at,
        s.is_visible_in_calendar
    FROM schedules s
    WHERE s.teacher_id = p_teacher_id
      AND s.date = p_date
      AND s.is_visible_in_calendar = TRUE
    ORDER BY s.start_time;
END;
$$;

-- 7.2 Get Client Statistics
CREATE OR REPLACE FUNCTION get_client_stats(p_teacher_id TEXT)
RETURNS TABLE (
    total_clients BIGINT,
    active_clients BIGINT,
    reserve_clients BIGINT,
    paused_clients BIGINT,
    completed_clients BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*) AS total_clients,
        COUNT(*) FILTER (WHERE type = 'client' AND status = 'active') AS active_clients,
        COUNT(*) FILTER (WHERE type = 'reserve') AS reserve_clients,
        COUNT(*) FILTER (WHERE status = 'paused') AS paused_clients,
        COUNT(*) FILTER (WHERE status = 'completed') AS completed_clients
    FROM clients
    WHERE teacher_id = p_teacher_id;
END;
$$;

-- 7.3 Get Session Time Statistics (통합: 수업 + 상담)
CREATE OR REPLACE FUNCTION get_session_time_stats(p_client_id TEXT)
RETURNS TABLE (
    weekly_minutes INT,
    monthly_minutes INT,
    total_minutes INT,
    total_sessions BIGINT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_today TEXT;
    v_week_start TEXT;
    v_month_start TEXT;
BEGIN
    v_today := TO_CHAR(CURRENT_DATE, 'YYYYMMDD');
    v_week_start := TO_CHAR(CURRENT_DATE - INTERVAL '7 days', 'YYYYMMDD');
    v_month_start := TO_CHAR(CURRENT_DATE - INTERVAL '30 days', 'YYYYMMDD');

    RETURN QUERY
    SELECT
        COALESCE(SUM(duration_minutes) FILTER (
            WHERE start_datetime >= v_week_start 
            AND start_datetime <= v_today
            AND category = 'completed'
        ), 0)::INT AS weekly_minutes,
        COALESCE(SUM(duration_minutes) FILTER (
            WHERE start_datetime >= v_month_start 
            AND start_datetime <= v_today
            AND category = 'completed'
        ), 0)::INT AS monthly_minutes,
        COALESCE(SUM(duration_minutes) FILTER (
            WHERE category = 'completed'
        ), 0)::INT AS total_minutes,
        COUNT(*) FILTER (WHERE category = 'completed') AS total_sessions
    FROM histories
    WHERE client_id = p_client_id;
END;
$$;

-- =============================================
-- 8. TRIGGER FUNCTIONS
-- =============================================

-- 8.1 Log Schedule Completion (수업/상담 완료 및 미출석 처리)
CREATE OR REPLACE FUNCTION log_schedule_completion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_duration INT;
    v_category TEXT;
    v_action TEXT;
    v_datetime TEXT;
BEGIN
    -- 상태가 completed 또는 noshow로 변경되었을 때만 실행
    IF (OLD.status IN ('scheduled') AND NEW.status IN ('completed', 'noshow')) THEN
        
        -- 카테고리 및 액션 결정
        IF NEW.status = 'completed' THEN
            v_category := 'completed';
            v_action := CASE 
                WHEN NEW.type = 'session' THEN '수업 완료'
                WHEN NEW.type = 'consultation' THEN '상담 완료'
            END;
        ELSIF NEW.status = 'noshow' THEN
            v_category := 'noshow';
            v_action := CASE 
                WHEN NEW.type = 'session' THEN '수업 미출석'
                WHEN NEW.type = 'consultation' THEN '상담 미출석'
            END;
        END IF;

        -- 날짜시간 형식: YYYYMMDD HH:mm
        v_datetime := NEW.date || ' ' || NEW.start_time;

        -- 소요 시간 계산 (완료 시에만)
        IF NEW.status = 'completed' THEN
            v_duration := EXTRACT(EPOCH FROM (
                TO_TIMESTAMP(NEW.date || ' ' || NEW.end_time, 'YYYYMMDD HH24:MI') -
                TO_TIMESTAMP(NEW.date || ' ' || NEW.start_time, 'YYYYMMDD HH24:MI')
            ))::INT / 60;
        ELSE
            v_duration := NULL;
        END IF;

        -- Histories 테이블에 기록 추가
        INSERT INTO histories (
            teacher_id,
            client_id,
            client_name,
            type,
            category,
            action,
            event_datetime,
            start_datetime,
            end_datetime,
            noshow_datetime,
            duration_minutes,
            memo,
            schedule_id
        ) VALUES (
            NEW.teacher_id,
            NEW.client_id,
            NEW.client_name,
            NEW.type,
            v_category,
            v_action,
            v_datetime,
            v_datetime,
            CASE WHEN NEW.status = 'completed' THEN NEW.date || ' ' || NEW.end_time ELSE NULL END,
            CASE WHEN NEW.status = 'noshow' THEN v_datetime ELSE NULL END,
            v_duration,
            NEW.memo,
            NEW.id
        );

        -- Activity Logs 테이블에 기록
        INSERT INTO activity_logs (
            teacher_name,
            type,
            action,
            details,
            occurred_at
        )
        SELECT 
            t.name,
            NEW.type,
            v_action,
            '내담자: ' || NEW.client_name || ' | 일시: ' || v_datetime,
            TIMEZONE('utc', NOW())
        FROM teachers t
        WHERE t.teacher_id = NEW.teacher_id;

        -- completed_at 타임스탬프 업데이트
        NEW.completed_at := TIMEZONE('utc', NOW());
    END IF;

    RETURN NEW;
END;
$$;

-- 8.2 Log Schedule Deletion (일정 삭제 시)
CREATE OR REPLACE FUNCTION log_schedule_deletion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_datetime TEXT;
    v_action TEXT;
BEGIN
    -- 캘린더에서만 삭제된 경우 (is_visible_in_calendar = FALSE)는 기록하지 않음
    IF OLD.is_visible_in_calendar = FALSE THEN
        RETURN OLD;
    END IF;

    -- 날짜시간 형식: YYYYMMDD HH:mm
    v_datetime := OLD.date || ' ' || OLD.start_time;
    
    v_action := CASE 
        WHEN OLD.type = 'session' THEN '수업 일정 삭제'
        WHEN OLD.type = 'consultation' THEN '상담 일정 삭제'
    END;

    -- Histories 테이블에 삭제 기록
    INSERT INTO histories (
        teacher_id,
        client_id,
        client_name,
        type,
        category,
        action,
        event_datetime,
        delete_datetime,
        memo,
        schedule_id
    ) VALUES (
        OLD.teacher_id,
        OLD.client_id,
        OLD.client_name,
        OLD.type,
        'deleted',
        v_action,
        v_datetime,
        v_datetime,
        OLD.memo,
        OLD.id
    );

    -- Activity Logs 테이블에 기록
    INSERT INTO activity_logs (
        teacher_name,
        type,
        action,
        details,
        occurred_at
    )
    SELECT 
        t.name,
        OLD.type,
        v_action,
        '내담자: ' || OLD.client_name || ' | 일시: ' || v_datetime,
        TIMEZONE('utc', NOW())
    FROM teachers t
    WHERE t.teacher_id = OLD.teacher_id;

    RETURN OLD;
END;
$$;

-- 8.3 Update Notice Timestamp
CREATE OR REPLACE FUNCTION update_notice_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$;

-- =============================================
-- 9. CREATE TRIGGERS
-- =============================================

CREATE TRIGGER trigger_log_schedule_completion
    AFTER UPDATE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_completion();

CREATE TRIGGER trigger_log_schedule_deletion
    BEFORE DELETE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_deletion();

CREATE TRIGGER trigger_update_notice_timestamp
    BEFORE UPDATE ON notices
    FOR EACH ROW
    EXECUTE FUNCTION update_notice_timestamp();

-- =============================================
-- 10. SAMPLE DATA
-- =============================================

-- Sample Teachers
INSERT INTO teachers (teacher_id, password, name, center, gender, age, contact, email, plan, status)
VALUES 
    ('teacher01', 'password123', '김선생', '서울센터', '여', 30, '010-1234-5678', 'teacher01@example.com', 'Pro Plan', 'Active'),
    ('teacher02', 'password456', '이선생', '부산센터', '남', 35, '010-9876-5432', 'teacher02@example.com', 'Basic Plan', 'Active'),
    ('admin', 'zxcasd123', '관리자', '본사', '여', 40, '010-0000-0000', 'admin@hahalab.com', 'Admin Plan', 'Active')
ON CONFLICT (teacher_id) DO NOTHING;

-- Sample Notices
INSERT INTO notices (type, title, content, date)
VALUES 
    ('update', '시스템 업데이트 안내', '<p>2026년 2월 15일 시스템 업데이트가 예정되어 있습니다.</p><p>새로운 기능이 추가됩니다.</p>', '20260215'),
    ('event', '신규 기능 추가', '<p>상담 이력 관리 기능이 추가되었습니다.</p><p>이제 상담 기록을 수업 이력과 함께 관리할 수 있습니다.</p>', '20260210'),
    ('maintenance', '정기 점검 안내', '<p>매주 일요일 새벽 2시~4시는 정기 점검 시간입니다.</p><p>서비스 이용에 참고 부탁드립니다.</p>', '20260201')
ON CONFLICT DO NOTHING;

-- Sample Play Contents
INSERT INTO play_contents (cat_id, title, url, tags, thumbnail, views)
VALUES 
    (1, '감각놀이 - 촉감 상자', 'https://example.com/video1', ARRAY['감각', '촉감', '탐색'], 'https://via.placeholder.com/400x300/FF6B6B/FFFFFF?text=감각놀이', 120),
    (2, '인지놀이 - 색깔 분류', 'https://example.com/video2', ARRAY['인지', '색깔', '분류'], 'https://via.placeholder.com/400x300/4ECDC4/FFFFFF?text=인지놀이', 95),
    (3, '사회성놀이 - 역할극', 'https://example.com/video3', ARRAY['사회성', '역할', '의사소통'], 'https://via.placeholder.com/400x300/95E1D3/FFFFFF?text=사회성놀이', 150)
ON CONFLICT DO NOTHING;

-- =============================================
-- 11. SCHEMA VERSION
-- =============================================

COMMENT ON SCHEMA public IS 'HAHA LAB Database Schema v4.0 - Final Complete - Updated 2026-02-10';

-- =============================================
-- 12. COMPLETION MESSAGE
-- =============================================

DO $$
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'HAHA LAB Database Schema v4.0';
    RAISE NOTICE 'Initialization Complete!';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'Features:';
    RAISE NOTICE '✓ Unified history tracking (session + consultation)';
    RAISE NOTICE '✓ Calendar visibility management (soft delete)';
    RAISE NOTICE '✓ Consultation to client migration support';
    RAISE NOTICE '✓ Enhanced schedule detail modal with history view';
    RAISE NOTICE '✓ Automatic history migration on type conversion';
    RAISE NOTICE '✓ Auto-scroll for weekly/daily calendar views';
    RAISE NOTICE '✓ Real-time session timer in GNB';
    RAISE NOTICE '✓ Secure password change with admin verification';
    RAISE NOTICE '========================================';
END $$;
