-- ============================================================
-- [HAHA LAB] Supabase Integrated Database Schema
-- Ver: Final Complete v3.1 (Updated 2026-02-10)
-- - Admin Features, Storage, RLS included
-- - Schedule status enhancements for completed tracking
-- - Client status management (active, paused, terminated, deleted)
-- - Histories tracking with detailed timestamps
-- - Statistics support (weekly, monthly, total)
-- ============================================================

-- ============================================================
-- [TABLE DEFINITIONS]
-- ============================================================

-- 1. 선생님 (Teachers) 테이블
CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    center TEXT,
    gender TEXT,
    age INT,
    contact TEXT,
    email TEXT,
    plan TEXT DEFAULT 'Basic Plan',
    status TEXT DEFAULT 'Active',
    memo TEXT,
    registered_clients INT DEFAULT 0
);

-- 2. 내담자 (Clients) 테이블
CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    gender TEXT,
    dob TEXT,
    age INT,
    contact TEXT,
    address TEXT,
    guardians JSONB,
    session_time INT DEFAULT 50,
    diagnosis TEXT,
    initial_consult TEXT,
    areas JSONB,
    memo TEXT,
    reserve_date TEXT,
    reserve_time TEXT
);

-- 3. 스케줄 (Schedules) 테이블
CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL,
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    status TEXT DEFAULT 'scheduled',
    memo TEXT,
    completed_at TIMESTAMP WITH TIME ZONE  -- NEW: 완료 시점 기록
);

-- 4. 공지사항 (Notices) 테이블
CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT,
    date TEXT,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 5. Play Lab 콘텐츠 (Play Contents) 테이블
CREATE TABLE IF NOT EXISTS play_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    cat_id TEXT NOT NULL,
    title TEXT NOT NULL,
    url TEXT,
    tags TEXT[],
    thumbnail TEXT,
    views INT DEFAULT 0,
    is_hidden BOOLEAN DEFAULT FALSE
);

-- 6. 활동 로그 (Activity Logs) 테이블
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_name TEXT,
    center_name TEXT,
    type TEXT,
    action TEXT,
    details TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 7. 내담자/예약자 이력 (Histories) 테이블 - ENHANCED
CREATE TABLE IF NOT EXISTS histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL,              -- 'session', 'consultation', 'noshow', 'reschedule', 'delete'
    category TEXT NOT NULL,          -- 'session_history', 'consultation_history'
    action TEXT NOT NULL,            -- '수업', '상담', '미출석', '일정삭제', '일정변경'
    
    -- 날짜 및 시간 정보
    date TEXT NOT NULL,              -- 일정 날짜 (YYYY-MM-DD)
    start_time TEXT,                 -- 시작 시간 (HH:MM)
    end_time TEXT,                   -- 종료 시간 (HH:MM)
    duration_minutes INT,            -- 총 소요 시간 (분)
    
    -- 일정 변경 정보
    original_date TEXT,              -- 원래 날짜
    changed_date TEXT,               -- 변경된 날짜
    original_time TEXT,              -- 원래 시간
    changed_time TEXT,               -- 변경된 시간
    
    -- 액션 시점 (NEW)
    action_time TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),  -- 미출석처리시점, 삭제시점, 변경시점
    
    details TEXT,
    memo TEXT
);


-- ============================================================
-- [INDEXES] 성능 최적화를 위한 인덱스
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_teachers_teacher_id ON teachers(teacher_id);
CREATE INDEX IF NOT EXISTS idx_teachers_status ON teachers(status);

CREATE INDEX IF NOT EXISTS idx_clients_teacher_id ON clients(teacher_id);
CREATE INDEX IF NOT EXISTS idx_clients_type ON clients(type);
CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status);
CREATE INDEX IF NOT EXISTS idx_clients_name ON clients(name);

CREATE INDEX IF NOT EXISTS idx_schedules_teacher_id ON schedules(teacher_id);
CREATE INDEX IF NOT EXISTS idx_schedules_client_id ON schedules(client_id);
CREATE INDEX IF NOT EXISTS idx_schedules_date ON schedules(date);
CREATE INDEX IF NOT EXISTS idx_schedules_status ON schedules(status);
CREATE INDEX IF NOT EXISTS idx_schedules_type ON schedules(type);
CREATE INDEX IF NOT EXISTS idx_schedules_date_time ON schedules(date, start_time);
CREATE INDEX IF NOT EXISTS idx_schedules_completed_at ON schedules(completed_at);

CREATE INDEX IF NOT EXISTS idx_play_contents_cat_id ON play_contents(cat_id);
CREATE INDEX IF NOT EXISTS idx_play_contents_is_hidden ON play_contents(is_hidden);

CREATE INDEX IF NOT EXISTS idx_notices_type ON notices(type);
CREATE INDEX IF NOT EXISTS idx_notices_is_hidden ON notices(is_hidden);

CREATE INDEX IF NOT EXISTS idx_histories_teacher_id ON histories(teacher_id);
CREATE INDEX IF NOT EXISTS idx_histories_client_id ON histories(client_id);
CREATE INDEX IF NOT EXISTS idx_histories_category ON histories(category);
CREATE INDEX IF NOT EXISTS idx_histories_date ON histories(date);
CREATE INDEX IF NOT EXISTS idx_histories_type ON histories(type);
CREATE INDEX IF NOT EXISTS idx_histories_action_time ON histories(action_time);


-- ============================================================
-- [Safety Checks] 기존 테이블 구조 보정
-- ============================================================
DO $$
BEGIN
    -- schedules 테이블에 completed_at 컬럼 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='schedules' AND column_name='completed_at') THEN
        ALTER TABLE schedules ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE;
    END IF;
    
    -- histories 테이블에 action_time 컬럼 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='histories' AND column_name='action_time') THEN
        ALTER TABLE histories ADD COLUMN action_time TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW());
    END IF;
    
    -- teachers 테이블에 status 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='teachers' AND column_name='status') THEN
        ALTER TABLE teachers ADD COLUMN status TEXT DEFAULT 'Active';
    END IF;
    
    -- notices 테이블에 is_hidden 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notices' AND column_name='is_hidden') THEN
        ALTER TABLE notices ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
    END IF;
    
    -- notices 테이블에 updated_at 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='notices' AND column_name='updated_at') THEN
        ALTER TABLE notices ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW());
    END IF;
    
    -- play_contents 테이블에 is_hidden 컬럼 없으면 추가
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='play_contents' AND column_name='is_hidden') THEN
        ALTER TABLE play_contents ADD COLUMN is_hidden BOOLEAN DEFAULT FALSE;
    END IF;
    
    -- schedules 테이블 status 기본값 확인
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='schedules' AND column_name='status') THEN
        ALTER TABLE schedules ADD COLUMN status TEXT DEFAULT 'scheduled';
    END IF;
    
    -- clients 테이블 status 기본값 확인
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='clients' AND column_name='status') THEN
        ALTER TABLE clients ADD COLUMN status TEXT DEFAULT 'active';
    END IF;
END $$;


-- ============================================================
-- [Data Integrity] 데이터 정합성 유지
-- ============================================================

DELETE FROM schedules 
WHERE client_id NOT IN (SELECT id::text FROM clients) 
AND client_id IS NOT NULL;

UPDATE teachers SET status = 'Active' WHERE LOWER(status) = 'active';
UPDATE teachers SET status = 'Paused' WHERE LOWER(status) = 'paused';
UPDATE teachers SET status = 'Suspended' WHERE LOWER(status) = 'suspended';

UPDATE clients SET status = 'active' WHERE status IS NULL OR status = '';
UPDATE schedules SET status = 'scheduled' WHERE status IS NULL OR status = '';


-- ============================================================
-- [Storage] 버킷 설정 및 정책
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) 
VALUES (
    'images', 
    'images', 
    true,
    15728640,
    ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE
SET 
    public = true,
    file_size_limit = 15728640,
    allowed_mime_types = ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']::text[];

DROP POLICY IF EXISTS "Public Access Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Images" ON storage.objects;

CREATE POLICY "Public Access Images" 
    ON storage.objects FOR SELECT 
    USING ( bucket_id = 'images' );

CREATE POLICY "Public Insert Images" 
    ON storage.objects FOR INSERT 
    WITH CHECK ( bucket_id = 'images' );

CREATE POLICY "Public Update Images" 
    ON storage.objects FOR UPDATE 
    USING ( bucket_id = 'images' )
    WITH CHECK ( bucket_id = 'images' );

CREATE POLICY "Public Delete Images" 
    ON storage.objects FOR DELETE 
    USING ( bucket_id = 'images' );


-- ============================================================
-- [Security] RLS (Row Level Security) 설정
-- ============================================================

ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE play_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE histories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow All Teachers" ON teachers;
DROP POLICY IF EXISTS "Allow All Clients" ON clients;
DROP POLICY IF EXISTS "Allow All Schedules" ON schedules;
DROP POLICY IF EXISTS "Allow All Notices" ON notices;
DROP POLICY IF EXISTS "Allow All Contents" ON play_contents;
DROP POLICY IF EXISTS "Allow All Logs" ON activity_logs;
DROP POLICY IF EXISTS "Allow All Histories" ON histories;

DROP POLICY IF EXISTS "Allow All Access Teachers" ON teachers;
DROP POLICY IF EXISTS "Allow All Access Clients" ON clients;
DROP POLICY IF EXISTS "Allow All Access Schedules" ON schedules;
DROP POLICY IF EXISTS "Allow All Access Notices" ON notices;
DROP POLICY IF EXISTS "Allow All Access Contents" ON play_contents;
DROP POLICY IF EXISTS "Allow All Access Logs" ON activity_logs;

CREATE POLICY "Allow All Teachers" 
    ON teachers FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Clients" 
    ON clients FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Schedules" 
    ON schedules FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Notices" 
    ON notices FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Contents" 
    ON play_contents FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Logs" 
    ON activity_logs FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Histories" 
    ON histories FOR ALL 
    USING (true) 
    WITH CHECK (true);


-- ============================================================
-- [SAMPLE DATA] 테스트용 샘플 데이터
-- ============================================================

INSERT INTO teachers (teacher_id, password, name, center, gender, age, contact, email, plan, status, registered_clients)
VALUES 
    ('teacher01', '1234', '김은애', '강남 본점', '여', 32, '010-1234-5678', 'kim@example.com', 'Pro Plan', 'Active', 8),
    ('teacher02', '1234', '이준호', '서초점', '남', 29, '010-2345-6789', 'lee@example.com', 'Basic Plan', 'Active', 5)
ON CONFLICT (teacher_id) DO NOTHING;

INSERT INTO notices (type, title, content, date, is_hidden)
VALUES 
    ('업데이트', '새로운 기능 업데이트 안내', '<p>상세한 이력 추적 시스템이 추가되었습니다.</p>', '2026-02-10', false),
    ('일반', 'HAHA LAB 시스템 오픈', '<p>HAHA LAB 시스템이 정식 오픈되었습니다.</p>', '2026-01-15', false)
ON CONFLICT DO NOTHING;

INSERT INTO play_contents (cat_id, title, url, tags, views, is_hidden)
VALUES 
    ('think', '기억력 향상 게임', 'https://example.com/memory-game', ARRAY['기억력', '인지', '주의력'], 120, false),
    ('sound', '음소 인식 훈련', 'https://example.com/phoneme-training', ARRAY['음소', '발음', '언어'], 85, false),
    ('listen', '청각 변별 훈련', 'https://example.com/auditory-training', ARRAY['청각', '집중력', '변별'], 95, false)
ON CONFLICT DO NOTHING;


-- ============================================================
-- [FUNCTIONS] 유용한 함수들
-- ============================================================

-- 특정 날짜의 스케줄 조회
CREATE OR REPLACE FUNCTION get_schedules_by_date(p_teacher_id TEXT, p_date TEXT)
RETURNS TABLE (
    id BIGINT,
    client_name TEXT,
    type TEXT,
    start_time TEXT,
    end_time TEXT,
    status TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT s.id, s.client_name, s.type, s.start_time, s.end_time, s.status
    FROM schedules s
    WHERE s.teacher_id = p_teacher_id 
    AND s.date = p_date
    AND s.status != 'deleted'
    ORDER BY s.start_time;
END;
$$ LANGUAGE plpgsql;

-- 내담자 통계 조회
CREATE OR REPLACE FUNCTION get_client_stats(p_teacher_id TEXT)
RETURNS TABLE (
    total_clients INT,
    active_clients INT,
    reserve_clients INT,
    paused_clients INT,
    terminated_clients INT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*)::INT AS total_clients,
        COUNT(CASE WHEN type = 'client' AND status = 'active' THEN 1 END)::INT AS active_clients,
        COUNT(CASE WHEN type = 'reserve' AND status = 'active' THEN 1 END)::INT AS reserve_clients,
        COUNT(CASE WHEN status = 'paused' THEN 1 END)::INT AS paused_clients,
        COUNT(CASE WHEN status = 'terminated' THEN 1 END)::INT AS terminated_clients
    FROM clients
    WHERE teacher_id = p_teacher_id
    AND status != 'deleted';
END;
$$ LANGUAGE plpgsql;

-- 내담자별 수업 통계 (주간/월간/총) - NEW
CREATE OR REPLACE FUNCTION get_client_session_stats(p_client_id TEXT)
RETURNS TABLE (
    weekly_minutes INT,
    monthly_minutes INT,
    total_minutes INT,
    total_sessions INT
) AS $$
DECLARE
    today DATE := CURRENT_DATE;
    week_start DATE := today - INTERVAL '7 days';
    month_start DATE := today - INTERVAL '30 days';
BEGIN
    RETURN QUERY
    SELECT 
        COALESCE(SUM(CASE WHEN h.date >= week_start::text THEN h.duration_minutes ELSE 0 END), 0)::INT AS weekly_minutes,
        COALESCE(SUM(CASE WHEN h.date >= month_start::text THEN h.duration_minutes ELSE 0 END), 0)::INT AS monthly_minutes,
        COALESCE(SUM(h.duration_minutes), 0)::INT AS total_minutes,
        COUNT(*)::INT AS total_sessions
    FROM histories h
    WHERE h.client_id = p_client_id
    AND h.category = 'session_history'
    AND h.action IN ('수업', '상담')
    AND h.duration_minutes IS NOT NULL;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- [TRIGGERS] 자동화 트리거
-- ============================================================

-- 스케줄 완료 시 이력 생성 (ENHANCED)
CREATE OR REPLACE FUNCTION log_schedule_completion()
RETURNS TRIGGER AS $$
DECLARE
    duration_mins INT;
    start_datetime TIMESTAMP;
    end_datetime TIMESTAMP;
    action_label TEXT;
BEGIN
    -- 수업/상담 완료 처리
    IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
        start_datetime := (NEW.date || ' ' || NEW.start_time)::TIMESTAMP;
        end_datetime := (NEW.date || ' ' || NEW.end_time)::TIMESTAMP;
        duration_mins := EXTRACT(EPOCH FROM (end_datetime - start_datetime)) / 60;
        
        -- completed_at 자동 설정
        NEW.completed_at := TIMEZONE('utc', NOW());
        
        -- 액션 레이블
        action_label := CASE WHEN NEW.type = 'reserve' THEN '상담' ELSE '수업' END;
        
        -- 활동 로그 생성
        INSERT INTO activity_logs (teacher_name, center_name, type, action, details)
        SELECT 
            t.name,
            t.center,
            CASE WHEN NEW.type = 'reserve' THEN '상담' ELSE '수업' END,
            CASE WHEN NEW.type = 'reserve' THEN '상담완료' ELSE '수업완료' END,
            NEW.client_name || ' (' || NEW.date || ' ' || NEW.start_time || ')'
        FROM teachers t
        WHERE t.teacher_id = NEW.teacher_id;
        
        -- 이력 생성
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            date, start_time, end_time, duration_minutes,
            action_time, details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            CASE WHEN NEW.type = 'reserve' THEN 'consultation' ELSE 'session' END,
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            action_label,
            NEW.date,
            NEW.start_time,
            NEW.end_time,
            duration_mins,
            NEW.completed_at,
            '정상 완료됨'
        );
    END IF;
    
    -- 미출석 처리
    IF NEW.status = 'noshow' AND OLD.status != 'noshow' THEN
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            date, start_time, end_time,
            action_time, details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            'noshow',
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            '미출석',
            NEW.date,
            NEW.start_time,
            NEW.end_time,
            TIMEZONE('utc', NOW()),
            '미출석 처리됨'
        );
    END IF;
    
    -- 일정 변경
    IF (NEW.date != OLD.date OR NEW.start_time != OLD.start_time OR NEW.end_time != OLD.end_time) 
       AND NEW.status != 'deleted' 
       AND OLD.status != 'deleted' THEN
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            date, start_time, end_time,
            original_date, changed_date,
            original_time, changed_time,
            action_time, details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            'reschedule',
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            '일정변경',
            NEW.date,
            NEW.start_time,
            NEW.end_time,
            OLD.date,
            NEW.date,
            OLD.start_time || ' ~ ' || OLD.end_time,
            NEW.start_time || ' ~ ' || NEW.end_time,
            TIMEZONE('utc', NOW()),
            '일정이 변경됨'
        );
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_log_schedule_completion ON schedules;
CREATE TRIGGER trigger_log_schedule_completion
    BEFORE UPDATE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_completion();

-- 스케줄 삭제 시 이력 생성
CREATE OR REPLACE FUNCTION log_schedule_deletion()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO histories (
        teacher_id, client_id, client_name, 
        type, category, action, 
        date, start_time, end_time,
        action_time, details
    ) VALUES (
        OLD.teacher_id, 
        OLD.client_id, 
        OLD.client_name,
        'delete',
        CASE WHEN OLD.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
        '일정삭제',
        OLD.date,
        OLD.start_time,
        OLD.end_time,
        TIMEZONE('utc', NOW()),
        '스케줄이 삭제됨'
    );
    
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_log_schedule_deletion ON schedules;
CREATE TRIGGER trigger_log_schedule_deletion
    BEFORE DELETE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_deletion();

-- Notices updated_at 자동 갱신
CREATE OR REPLACE FUNCTION update_notice_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_notice_timestamp ON notices;
CREATE TRIGGER trigger_update_notice_timestamp
    BEFORE UPDATE ON notices
    FOR EACH ROW
    EXECUTE FUNCTION update_notice_timestamp();


-- ============================================================
-- [SCHEMA VERSION]
-- ============================================================
COMMENT ON SCHEMA public IS 'HAHA LAB Database Schema v3.1 - Updated 2026-02-10';


-- ============================================================
-- [완료]
-- 데이터베이스 스키마 초기화가 완료되었습니다.
-- ============================================================
