-- ============================================================
-- [HAHA LAB] Complete Database Schema
-- Ver: 3.3.0 (Rebuilt from scratch - 2026-02-10)
-- 
-- Based on comprehensive analysis of:
-- - index.html (User Dashboard)
-- - admin.html (Administrator Console)
--
-- Features:
-- - Teachers & Clients Management
-- - Schedule System with Status Tracking
-- - History Tracking (YYYYMMDD HH:mm format)
-- - Notice System (with hide/show)
-- - Play Lab Contents Management
-- - Activity Logs
-- - Storage Integration
-- - RLS Policies
-- ============================================================

-- ============================================================
-- STEP 1: Clean Existing Objects (Fresh Start)
-- ============================================================

-- Drop existing triggers first
DROP TRIGGER IF EXISTS trigger_log_schedule_completion ON schedules;
DROP TRIGGER IF EXISTS trigger_log_schedule_deletion ON schedules;
DROP TRIGGER IF EXISTS trigger_update_notice_timestamp ON notices;

-- Drop existing functions
DROP FUNCTION IF EXISTS log_schedule_completion() CASCADE;
DROP FUNCTION IF EXISTS log_schedule_deletion() CASCADE;
DROP FUNCTION IF EXISTS update_notice_timestamp() CASCADE;
DROP FUNCTION IF EXISTS get_schedules_by_date(TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_client_stats(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_session_time_stats(TEXT) CASCADE;

-- Drop existing tables (with CASCADE to remove dependencies)
DROP TABLE IF EXISTS histories CASCADE;
DROP TABLE IF EXISTS activity_logs CASCADE;
DROP TABLE IF EXISTS play_contents CASCADE;
DROP TABLE IF EXISTS notices CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS teachers CASCADE;


-- ============================================================
-- STEP 2: Create Tables
-- ============================================================

-- 1. Teachers Table (선생님)
-- Used by: index.html (authentication), admin.html (teacher management)
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT UNIQUE NOT NULL,        -- Login ID
    password TEXT NOT NULL,                 -- Password (should be hashed in production)
    name TEXT NOT NULL,
    center TEXT,
    gender TEXT,
    age INT,
    contact TEXT,
    email TEXT,
    plan TEXT DEFAULT 'Basic Plan',         -- 'Basic Plan', 'Pro Plan', 'Enterprise'
    status TEXT DEFAULT 'Active',           -- 'Active', 'Paused', 'Suspended'
    memo TEXT,
    registered_clients INT DEFAULT 0
);

COMMENT ON TABLE teachers IS 'Teacher accounts with authentication and subscription info';
COMMENT ON COLUMN teachers.teacher_id IS 'Unique login ID';
COMMENT ON COLUMN teachers.status IS 'Active: normal use, Paused: temporarily suspended, Suspended: admin blocked';


-- 2. Clients Table (내담자/예약자)
-- Used by: index.html (client management, schedule creation)
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,               -- Owner teacher ID
    name TEXT NOT NULL,
    type TEXT NOT NULL,                     -- 'client' (regular), 'reserve' (consultation pending)
    status TEXT DEFAULT 'active',           -- 'active', 'paused', 'terminated', 'deleted'
    gender TEXT,
    dob TEXT,                               -- YYYY-MM-DD format
    age INT,
    contact TEXT,
    address TEXT,
    guardians JSONB,                        -- Guardian info array: [{"name":"","contact":"","relation":""}]
    session_time INT DEFAULT 50,            -- Default session duration (minutes)
    diagnosis TEXT,                         -- Diagnosis information
    initial_consult TEXT,                   -- Initial consultation notes
    areas JSONB,                            -- Development areas: {"lang":[],"cogn":[],"behv":[]}
    memo TEXT,
    reserve_date TEXT,                      -- Consultation date (for reserve type)
    reserve_time TEXT                       -- Consultation time (for reserve type)
);

COMMENT ON TABLE clients IS 'Client and consultation reservation records';
COMMENT ON COLUMN clients.type IS 'client: regular student, reserve: pending consultation';
COMMENT ON COLUMN clients.status IS 'active: normal, paused: temporarily stopped, terminated: completed, deleted: removed';
COMMENT ON COLUMN clients.guardians IS 'JSON array of guardian information';
COMMENT ON COLUMN clients.areas IS 'Development area tags for tracking';


-- 3. Schedules Table (스케줄)
-- Used by: index.html (calendar management, session tracking)
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL,                     -- 'client' (session), 'reserve' (consultation)
    date TEXT NOT NULL,                     -- YYYY-MM-DD format
    start_time TEXT NOT NULL,               -- HH:MM format (24-hour)
    end_time TEXT NOT NULL,                 -- HH:MM format (24-hour)
    status TEXT DEFAULT 'scheduled',        -- 'scheduled', 'in-progress', 'completed', 'noshow', 'deleted'
    memo TEXT
);

COMMENT ON TABLE schedules IS 'Session and consultation schedule records';
COMMENT ON COLUMN schedules.type IS 'client: regular session, reserve: consultation';
COMMENT ON COLUMN schedules.status IS 'scheduled: pending, in-progress: ongoing, completed: finished, noshow: absent';


-- 4. Histories Table (이력)
-- Used by: index.html (client detail page - session history, consultation history tabs)
CREATE TABLE histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_id TEXT NOT NULL,
    client_id TEXT NOT NULL,
    client_name TEXT NOT NULL,
    type TEXT NOT NULL,                     -- 'session', 'consultation', 'noshow', 'reschedule', 'delete'
    category TEXT NOT NULL,                 -- 'session_history', 'consultation_history'
    action TEXT NOT NULL,                   -- '수업완료', '상담완료', '일정변경', '미출석', '일정삭제'
    
    -- YYYYMMDD HH:mm format fields (for frontend display)
    event_datetime TEXT,                    -- Event occurrence time
    start_datetime TEXT,                    -- Session/Consultation start time
    end_datetime TEXT,                      -- Session/Consultation end time
    noshow_datetime TEXT,                   -- No-show marked time
    delete_datetime TEXT,                   -- Schedule deletion time
    reschedule_datetime TEXT,               -- Reschedule action time
    original_datetime TEXT,                 -- Original schedule (before change)
    changed_datetime TEXT,                  -- New schedule (after change)
    
    duration_minutes INT,                   -- Duration in minutes (for statistics)
    details TEXT,
    memo TEXT
);

COMMENT ON TABLE histories IS 'Complete history tracking for sessions, consultations, and schedule changes';
COMMENT ON COLUMN histories.category IS 'session_history: for clients, consultation_history: for reserves';
COMMENT ON COLUMN histories.start_datetime IS 'Format: YYYYMMDD HH:mm (e.g., 20260210 14:30)';
COMMENT ON COLUMN histories.duration_minutes IS 'Used for calculating weekly/monthly/total session time statistics';


-- 5. Notices Table (공지사항)
-- Used by: index.html (notice page), admin.html (notice management with hide/show)
CREATE TABLE notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    type TEXT NOT NULL,                     -- '일반', '업데이트', '점검', '이벤트'
    title TEXT NOT NULL,
    content TEXT,                           -- HTML content supported
    date TEXT,                              -- Notice date (YYYY-MM-DD)
    is_hidden BOOLEAN DEFAULT FALSE         -- Admin hide/show toggle
);

COMMENT ON TABLE notices IS 'System notices with admin visibility control';
COMMENT ON COLUMN notices.is_hidden IS 'Admin can hide notices without deleting them';


-- 6. Play Lab Contents Table (콘텐츠)
-- Used by: index.html (session mode - play lab), admin.html (content management)
CREATE TABLE play_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    cat_id TEXT NOT NULL,                   -- 'think', 'sound', 'listen', 'see', 'speak', 'life', 'art'
    title TEXT NOT NULL,
    url TEXT,                               -- Content URL (iframe source)
    tags TEXT[],                            -- PostgreSQL array: ['기억력', '인지', '주의력']
    thumbnail TEXT,                         -- Thumbnail image URL (stored in Supabase Storage)
    views INT DEFAULT 0,
    is_hidden BOOLEAN DEFAULT FALSE         -- Admin hide/show toggle
);

COMMENT ON TABLE play_contents IS 'Educational content library for 7 categories';
COMMENT ON COLUMN play_contents.cat_id IS 'Category: think/sound/listen/see/speak/life/art';
COMMENT ON COLUMN play_contents.tags IS 'Array of tag strings for search/filter';


-- 7. Activity Logs Table (활동 로그)
-- Used by: admin.html (activity logs view)
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    teacher_name TEXT,
    center_name TEXT,
    type TEXT,                              -- '시스템', '수업', '학생관리', '상담'
    action TEXT,                            -- '로그인', '수업완료', '상담완료', '학생추가', etc.
    details TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

COMMENT ON TABLE activity_logs IS 'System-wide activity tracking for admin monitoring';


-- ============================================================
-- STEP 3: Create Indexes (Performance Optimization)
-- ============================================================

-- Teachers indexes
CREATE INDEX idx_teachers_teacher_id ON teachers(teacher_id);
CREATE INDEX idx_teachers_status ON teachers(status);

-- Clients indexes
CREATE INDEX idx_clients_teacher_id ON clients(teacher_id);
CREATE INDEX idx_clients_type ON clients(type);
CREATE INDEX idx_clients_status ON clients(status);
CREATE INDEX idx_clients_name ON clients(name);

-- Schedules indexes
CREATE INDEX idx_schedules_teacher_id ON schedules(teacher_id);
CREATE INDEX idx_schedules_client_id ON schedules(client_id);
CREATE INDEX idx_schedules_date ON schedules(date);
CREATE INDEX idx_schedules_status ON schedules(status);
CREATE INDEX idx_schedules_type ON schedules(type);
CREATE INDEX idx_schedules_date_time ON schedules(date, start_time);

-- Histories indexes
CREATE INDEX idx_histories_teacher_id ON histories(teacher_id);
CREATE INDEX idx_histories_client_id ON histories(client_id);
CREATE INDEX idx_histories_category ON histories(category);
CREATE INDEX idx_histories_type ON histories(type);
CREATE INDEX idx_histories_start_datetime ON histories(start_datetime);

-- Notices indexes
CREATE INDEX idx_notices_type ON notices(type);
CREATE INDEX idx_notices_is_hidden ON notices(is_hidden);
CREATE INDEX idx_notices_created_at ON notices(created_at DESC);

-- Play Contents indexes
CREATE INDEX idx_play_contents_cat_id ON play_contents(cat_id);
CREATE INDEX idx_play_contents_is_hidden ON play_contents(is_hidden);

-- Activity Logs indexes
CREATE INDEX idx_activity_logs_occurred_at ON activity_logs(occurred_at DESC);
CREATE INDEX idx_activity_logs_type ON activity_logs(type);


-- ============================================================
-- STEP 4: Functions
-- ============================================================

-- Function 1: Get schedules by date
-- Used by: index.html (calendar views)
CREATE OR REPLACE FUNCTION get_schedules_by_date(p_teacher_id TEXT, p_date TEXT)
RETURNS TABLE (
    id BIGINT,
    client_name TEXT,
    type TEXT,
    start_time TEXT,
    end_time TEXT,
    status TEXT
) 
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        s.id, 
        s.client_name, 
        s.type, 
        s.start_time, 
        s.end_time, 
        s.status
    FROM schedules s
    WHERE s.teacher_id = p_teacher_id 
    AND s.date = p_date
    AND s.status != 'deleted'
    ORDER BY s.start_time;
END;
$$;

COMMENT ON FUNCTION get_schedules_by_date IS 'Retrieve all schedules for a specific teacher and date';


-- Function 2: Get client statistics
-- Used by: index.html (dashboard statistics), admin.html (teacher detail)
CREATE OR REPLACE FUNCTION get_client_stats(p_teacher_id TEXT)
RETURNS TABLE (
    total_clients INT,
    active_clients INT,
    reserve_clients INT,
    paused_clients INT,
    terminated_clients INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        COUNT(*)::INT AS total_clients,
        COUNT(CASE WHEN type = 'client' AND status = 'active' THEN 1 END)::INT AS active_clients,
        COUNT(CASE WHEN type = 'reserve' AND status = 'active' THEN 1 END)::INT AS reserve_clients,
        COUNT(CASE WHEN status = 'paused' THEN 1 END)::INT AS paused_clients,
        COUNT(CASE WHEN status = 'terminated' THEN 1 END)::INT AS terminated_clients
    FROM clients
    WHERE teacher_id = p_teacher_id
    AND status != 'deleted';
END;
$$;

COMMENT ON FUNCTION get_client_stats IS 'Calculate client statistics by status for a teacher';


-- Function 3: Get session time statistics (weekly/monthly/total)
-- Used by: index.html (client detail page - session history tab statistics)
CREATE OR REPLACE FUNCTION get_session_time_stats(p_client_id TEXT)
RETURNS TABLE (
    weekly_minutes INT,
    monthly_minutes INT,
    total_minutes INT
)
LANGUAGE plpgsql
AS $$
DECLARE
    week_start TEXT;
    month_start TEXT;
BEGIN
    -- Get start of current week (Monday) in YYYYMMDD format
    week_start := TO_CHAR(DATE_TRUNC('week', CURRENT_DATE), 'YYYYMMDD');
    
    -- Get start of current month in YYYYMMDD format
    month_start := TO_CHAR(DATE_TRUNC('month', CURRENT_DATE), 'YYYYMMDD');
    
    RETURN QUERY
    SELECT 
        -- Weekly: sum of duration_minutes where start_datetime >= week_start
        COALESCE(SUM(CASE 
            WHEN SUBSTRING(start_datetime, 1, 8) >= week_start 
            THEN duration_minutes 
            ELSE 0 
        END), 0)::INT AS weekly_minutes,
        
        -- Monthly: sum of duration_minutes where start_datetime >= month_start
        COALESCE(SUM(CASE 
            WHEN SUBSTRING(start_datetime, 1, 8) >= month_start 
            THEN duration_minutes 
            ELSE 0 
        END), 0)::INT AS monthly_minutes,
        
        -- Total: sum of all duration_minutes
        COALESCE(SUM(duration_minutes), 0)::INT AS total_minutes
    FROM histories
    WHERE client_id = p_client_id
    AND category = 'session_history'
    AND action = '수업완료'
    AND start_datetime IS NOT NULL;
END;
$$;

COMMENT ON FUNCTION get_session_time_stats IS 'Calculate weekly, monthly, and total session minutes for a client';


-- ============================================================
-- STEP 5: Triggers and Trigger Functions
-- ============================================================

-- Trigger Function 1: Log schedule completion, no-show, and reschedule
-- Automatically creates history records when schedule status changes
CREATE OR REPLACE FUNCTION log_schedule_completion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    duration_mins INT;
    start_dt TIMESTAMP;
    end_dt TIMESTAMP;
    start_fmt TEXT;
    end_fmt TEXT;
    now_fmt TEXT;
BEGIN
    -- Current time in Asia/Seoul timezone, formatted as YYYYMMDD HH:mm
    now_fmt := TO_CHAR(TIMEZONE('Asia/Seoul', NOW()), 'YYYYMMDD HH24:MI');
    
    -- ===== CASE 1: Session/Consultation Completed =====
    IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
        -- Calculate duration in minutes
        start_dt := (NEW.date || ' ' || NEW.start_time)::TIMESTAMP;
        end_dt := (NEW.date || ' ' || NEW.end_time)::TIMESTAMP;
        duration_mins := EXTRACT(EPOCH FROM (end_dt - start_dt)) / 60;
        
        -- Format datetime as YYYYMMDD HH:mm
        start_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.start_time;
        end_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.end_time;
        
        -- Insert activity log
        INSERT INTO activity_logs (teacher_name, center_name, type, action, details)
        SELECT 
            t.name,
            t.center,
            CASE WHEN NEW.type = 'reserve' THEN '상담' ELSE '수업' END,
            CASE WHEN NEW.type = 'reserve' THEN '상담완료' ELSE '수업완료' END,
            NEW.client_name || ' (' || start_fmt || ' ~ ' || end_fmt || ')'
        FROM teachers t
        WHERE t.teacher_id = NEW.teacher_id;
        
        -- Insert history record
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            event_datetime, start_datetime, end_datetime, duration_minutes, 
            details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            CASE WHEN NEW.type = 'reserve' THEN 'consultation' ELSE 'session' END,
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            CASE WHEN NEW.type = 'reserve' THEN '상담완료' ELSE '수업완료' END,
            now_fmt,
            start_fmt,
            end_fmt,
            duration_mins,
            '정상 완료됨'
        );
    END IF;
    
    -- ===== CASE 2: No-Show Marked =====
    IF NEW.status = 'noshow' AND OLD.status != 'noshow' THEN
        start_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.start_time;
        
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            event_datetime, start_datetime, noshow_datetime,
            details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            'noshow',
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            '미출석',
            now_fmt,
            start_fmt,
            now_fmt,
            '미출석 처리됨'
        );
    END IF;
    
    -- ===== CASE 3: Schedule Rescheduled =====
    IF (NEW.date != OLD.date OR NEW.start_time != OLD.start_time) 
       AND NEW.status != 'deleted' 
       AND OLD.status != 'deleted' THEN
        
        start_fmt := REPLACE(OLD.date, '-', '') || ' ' || OLD.start_time;
        end_fmt := REPLACE(NEW.date, '-', '') || ' ' || NEW.start_time;
        
        INSERT INTO histories (
            teacher_id, client_id, client_name, 
            type, category, action, 
            event_datetime, original_datetime, changed_datetime, reschedule_datetime,
            details
        ) VALUES (
            NEW.teacher_id, 
            NEW.client_id, 
            NEW.client_name,
            'reschedule',
            CASE WHEN NEW.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
            '일정변경',
            now_fmt,
            start_fmt,
            end_fmt,
            now_fmt,
            '일정이 변경됨'
        );
    END IF;
    
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION log_schedule_completion IS 'Automatically log history when schedule status changes (completed/noshow/rescheduled)';


-- Trigger Function 2: Log schedule deletion
-- Automatically creates history record when schedule is deleted
CREATE OR REPLACE FUNCTION log_schedule_deletion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    start_fmt TEXT;
    now_fmt TEXT;
BEGIN
    -- Format datetime as YYYYMMDD HH:mm
    start_fmt := REPLACE(OLD.date, '-', '') || ' ' || OLD.start_time;
    now_fmt := TO_CHAR(TIMEZONE('Asia/Seoul', NOW()), 'YYYYMMDD HH24:MI');
    
    INSERT INTO histories (
        teacher_id, client_id, client_name, 
        type, category, action, 
        event_datetime, start_datetime, delete_datetime,
        details
    ) VALUES (
        OLD.teacher_id, 
        OLD.client_id, 
        OLD.client_name,
        'delete',
        CASE WHEN OLD.type = 'reserve' THEN 'consultation_history' ELSE 'session_history' END,
        '일정삭제',
        now_fmt,
        start_fmt,
        now_fmt,
        '스케줄이 삭제됨'
    );
    
    RETURN OLD;
END;
$$;

COMMENT ON FUNCTION log_schedule_deletion IS 'Automatically log history when schedule is deleted';


-- Trigger Function 3: Update notice timestamp
-- Automatically updates updated_at when notice is modified
CREATE OR REPLACE FUNCTION update_notice_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION update_notice_timestamp IS 'Automatically update updated_at timestamp when notice is modified';


-- Create Triggers
CREATE TRIGGER trigger_log_schedule_completion
    AFTER UPDATE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_completion();

CREATE TRIGGER trigger_log_schedule_deletion
    BEFORE DELETE ON schedules
    FOR EACH ROW
    EXECUTE FUNCTION log_schedule_deletion();

CREATE TRIGGER trigger_update_notice_timestamp
    BEFORE UPDATE ON notices
    FOR EACH ROW
    EXECUTE FUNCTION update_notice_timestamp();


-- ============================================================
-- STEP 6: Row Level Security (RLS)
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE histories ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE play_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Create permissive policies (Allow All for development)
-- NOTE: In production, implement teacher_id-based filtering

CREATE POLICY "Allow All Teachers" 
    ON teachers FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Clients" 
    ON clients FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Schedules" 
    ON schedules FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Histories" 
    ON histories FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Notices" 
    ON notices FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Contents" 
    ON play_contents FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Allow All Logs" 
    ON activity_logs FOR ALL 
    USING (true) 
    WITH CHECK (true);


-- ============================================================
-- STEP 7: Storage Bucket Configuration
-- ============================================================

-- Create 'images' bucket for thumbnails and uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) 
VALUES (
    'images', 
    'images', 
    true,
    15728640,  -- 15MB limit
    ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']::text[]
)
ON CONFLICT (id) DO UPDATE
SET 
    public = true,
    file_size_limit = 15728640,
    allowed_mime_types = ARRAY['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp']::text[];

-- Drop existing storage policies
DROP POLICY IF EXISTS "Public Access Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Insert Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Update Images" ON storage.objects;
DROP POLICY IF EXISTS "Public Delete Images" ON storage.objects;

-- Create storage access policies
CREATE POLICY "Public Access Images" 
    ON storage.objects FOR SELECT 
    USING ( bucket_id = 'images' );

CREATE POLICY "Public Insert Images" 
    ON storage.objects FOR INSERT 
    WITH CHECK ( bucket_id = 'images' );

CREATE POLICY "Public Update Images" 
    ON storage.objects FOR UPDATE 
    USING ( bucket_id = 'images' )
    WITH CHECK ( bucket_id = 'images' );

CREATE POLICY "Public Delete Images" 
    ON storage.objects FOR DELETE 
    USING ( bucket_id = 'images' );


-- ============================================================
-- STEP 8: Sample Data (Optional - for testing)
-- ============================================================

-- Insert sample teachers
INSERT INTO teachers (teacher_id, password, name, center, gender, age, contact, email, plan, status, registered_clients)
VALUES 
    ('teacher01', '1234', '김은애', '강남 본점', '여', 32, '010-1234-5678', 'kim@example.com', 'Pro Plan', 'Active', 8),
    ('teacher02', '1234', '이준호', '서초점', '남', 29, '010-2345-6789', 'lee@example.com', 'Basic Plan', 'Active', 5)
ON CONFLICT (teacher_id) DO NOTHING;

-- Insert sample notices
INSERT INTO notices (type, title, content, date, is_hidden)
VALUES 
    ('업데이트', '새로운 기능 업데이트 안내', '<p>스케줄 완료 상태 표시 기능이 추가되었습니다.</p><p>- 완료된 수업/상담은 회색으로 표시됩니다.</p><p>- 완료 처리 버튼이 추가되었습니다.</p>', '2026-02-10', false),
    ('일반', 'HAHA LAB 시스템 오픈', '<p>HAHA LAB 시스템이 정식 오픈되었습니다.</p><p>많은 이용 부탁드립니다.</p>', '2026-01-15', false),
    ('이벤트', '신규 가입 이벤트', '<p>2월 말까지 신규 가입 선생님께 첫 달 무료 제공!</p>', '2026-02-01', false)
ON CONFLICT DO NOTHING;

-- Insert sample play lab contents
INSERT INTO play_contents (cat_id, title, url, tags, views, is_hidden)
VALUES 
    ('think', '기억력 향상 게임', 'https://example.com/memory-game', ARRAY['기억력', '인지', '주의력'], 120, false),
    ('sound', '음소 인식 훈련', 'https://example.com/phoneme-training', ARRAY['음소', '발음', '언어'], 85, false),
    ('listen', '청각 변별 훈련', 'https://example.com/auditory-training', ARRAY['청각', '집중력', '변별'], 95, false),
    ('see', '시지각 게임', 'https://example.com/visual-perception', ARRAY['시지각', '관찰력', '집중력'], 78, false),
    ('speak', '어휘 확장 활동', 'https://example.com/vocabulary', ARRAY['어휘', '표현', '언어'], 102, false),
    ('life', '생활 기술 훈련', 'https://example.com/daily-skills', ARRAY['일상', '사회성', '적응'], 65, false),
    ('art', '창의 미술 활동', 'https://example.com/art-therapy', ARRAY['미술', '창의력', '소근육'], 88, false)
ON CONFLICT DO NOTHING;


-- ============================================================
-- STEP 9: Data Integrity Maintenance
-- ============================================================

-- Remove orphaned schedules (schedules without matching clients)
DELETE FROM schedules 
WHERE client_id NOT IN (SELECT id::text FROM clients) 
AND client_id IS NOT NULL;

-- Normalize status values
UPDATE teachers SET status = 'Active' WHERE LOWER(status) = 'active';
UPDATE teachers SET status = 'Paused' WHERE LOWER(status) = 'paused';
UPDATE teachers SET status = 'Suspended' WHERE LOWER(status) = 'suspended';

UPDATE clients SET status = 'active' WHERE status IS NULL OR status = '';
UPDATE schedules SET status = 'scheduled' WHERE status IS NULL OR status = '';


-- ============================================================
-- STEP 10: Verification Queries (Optional - for testing)
-- ============================================================

-- These are commented out, but can be run to verify the schema

-- Verify table creation
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;

-- Verify column structure for histories table
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = 'histories' ORDER BY ordinal_position;

-- Test get_session_time_stats function
-- SELECT * FROM get_session_time_stats('1');

-- Check indexes
-- SELECT indexname, tablename FROM pg_indexes WHERE schemaname = 'public' ORDER BY tablename, indexname;

-- Check triggers
-- SELECT trigger_name, event_manipulation, event_object_table FROM information_schema.triggers WHERE trigger_schema = 'public';


-- ============================================================
-- COMPLETION
-- ============================================================

-- Add schema version comment
COMMENT ON SCHEMA public IS 'HAHA LAB Database Schema v3.3.0 - Complete Rebuild - 2026-02-10';

-- Success message
DO $$ 
BEGIN 
    RAISE NOTICE '==================================================================';
    RAISE NOTICE 'HAHA LAB Database Schema v3.3.0 - Installation Complete!';
    RAISE NOTICE '==================================================================';
    RAISE NOTICE 'Tables Created: 7 (teachers, clients, schedules, histories, notices, play_contents, activity_logs)';
    RAISE NOTICE 'Functions Created: 3 (get_schedules_by_date, get_client_stats, get_session_time_stats)';
    RAISE NOTICE 'Triggers Created: 3 (completion tracking, deletion tracking, notice timestamp)';
    RAISE NOTICE 'Indexes Created: 25+ (for optimal query performance)';
    RAISE NOTICE 'Storage Bucket: images (15MB limit, public access)';
    RAISE NOTICE 'RLS Policies: Enabled with permissive policies (configure for production)';
    RAISE NOTICE '';
    RAISE NOTICE 'Sample data inserted: 2 teachers, 3 notices, 7 play lab contents';
    RAISE NOTICE '';
    RAISE NOTICE 'Next Steps:';
    RAISE NOTICE '1. Verify installation: SELECT * FROM teachers;';
    RAISE NOTICE '2. Test history tracking: Create and complete a schedule';
    RAISE NOTICE '3. Test statistics: SELECT * FROM get_session_time_stats(''client_id'');';
    RAISE NOTICE '4. Configure production RLS policies (teacher_id filtering)';
    RAISE NOTICE '';
    RAISE NOTICE 'Ready for use with index.html and admin.html!';
    RAISE NOTICE '==================================================================';
END $$;
